In [1]:
import pandas as pd
dataset= pd.read_csv("whatsapp_output.csv", index_col=False)
dataset

,Date,Time,Name,Chat,scores,positive,negative,compound,neutral,com_score,datetime,is_flirt
0,29/04/25,11:15,Dineshkumar,What help do you need,"{'neg': 0.0, 'neu': 0.597, 'pos': 0.403, 'comp...",0.403,0.0,0.4019,0.597,positive,2025-04-29 11:15:00,False
1,29/04/25,12:14,Jayabharathi,One kiss,"{'neg': 0.0, 'neu': 0.263, 'pos': 0.737, 'comp...",0.737,0.0,0.4215,0.263,positive,2025-04-29 12:14:00,True
2,29/04/25,12:17,Jayabharathi,https://www.instagram.com/reel/Cb2VhXDPtaW/?i...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.000,0.0,0.0000,1.000,positive,2025-04-29 12:17:00,False
3,29/04/25,12:25,Jayabharathi,Like this,"{'neg': 0.0, 'neu': 0.286, 'pos': 0.714, 'comp...",0.714,0.0,0.3612,0.286,positive,2025-04-29 12:25:00,False
4,29/04/25,13:37,Dineshkumar,<Media omitted>,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.000,0.0,0.0000,1.000,positive,2025-04-29 13:37:00,False
...,...,...,...,...,...,...,...,...,...,...,...,...
1037,16/04/26,11:48,Dineshkumar,,"{'neg': 0.0, 'neu': 0.0, 'pos': 0.0, 'compound...",0.000,0.0,0.0000,0.000,positive,2026-04-16 11:48:00,False
1038,16/04/26,11:48,Dineshkumar,Trois-1764,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.000,0.0,0.0000,1.000,positive,2026-04-16 11:48:00,False
1039,16/04/26,11:48,Dineshkumar,<Media omitted>,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.000,0.0,0.0000,1.000,positive,2026-04-16 11:48:00,False
1040,16/04/26,11:48,Dineshkumar,<Media omitted>,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.000,0.0,0.0000,1.000,positive,2026-04-16 11:48:00,False
1041,16/04/26,11:49,Jayabharathi,Okay,"{'neg': 0.0, 'neu': 0.0, 'pos': 1.0, 'compound...",1.000,0.0,0.2263,0.000,positive,2026-04-16 11:49:00,False

In [2]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(max_df=0.95, min_df=2, stop_words='english')
dtm = tfidf.fit_transform(dataset['Chat'])
dtm

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 2258 stored elements and shape (1042, 385)>

In [3]:
from sklearn.decomposition import LatentDirichletAllocation
LDA = LatentDirichletAllocation(n_components=5, random_state=42)
LDA.fit(dtm)

LatentDirichletAllocation(n_components=5, random_state=42)

In [5]:
for index, topic in enumerate(LDA.components_):
    result = ([tfidf.get_feature_names_out()[i] for i in topic.argsort()[-10:]])
    print(result)

['ok', 'send', 'month', 'irukku', 'panren', 'na', 'yes', 'message', 'deleted', 'baby']
['mari', 'solunga', 'buy', 'ithu', 'shorts', 'youtube', 'meeting', 'si', 'com', 'https']
['ma', 'hi', 'gpay', 'know', 'na', 'iruku', 'send', 'okay', 'ah', 'ok']
['set', 'kuda', 'enaku', 'youtu', 'dp', 'vanga', 'sorry', 'hey', 'media', 'omitted']
['ila', 'dhan', 'nu', 'venam', 'ne', 'enaku', 'otp', 'na', 'la', 'enna']

In [7]:
topic_results=LDA.transform(dtm)
dataset["Topic"]=topic_results.argmax(axis=1)

In [8]:
dataset

,Date,Time,Name,Chat,scores,positive,negative,compound,neutral,com_score,datetime,is_flirt,Topic
0,29/04/25,11:15,Dineshkumar,What help do you need,"{'neg': 0.0, 'neu': 0.597, 'pos': 0.403, 'comp...",0.403,0.0,0.4019,0.597,positive,2025-04-29 11:15:00,False,1
1,29/04/25,12:14,Jayabharathi,One kiss,"{'neg': 0.0, 'neu': 0.263, 'pos': 0.737, 'comp...",0.737,0.0,0.4215,0.263,positive,2025-04-29 12:14:00,True,0
2,29/04/25,12:17,Jayabharathi,https://www.instagram.com/reel/Cb2VhXDPtaW/?i...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.000,0.0,0.0000,1.000,positive,2025-04-29 12:17:00,False,0
3,29/04/25,12:25,Jayabharathi,Like this,"{'neg': 0.0, 'neu': 0.286, 'pos': 0.714, 'comp...",0.714,0.0,0.3612,0.286,positive,2025-04-29 12:25:00,False,2
4,29/04/25,13:37,Dineshkumar,<Media omitted>,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.000,0.0,0.0000,1.000,positive,2025-04-29 13:37:00,False,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1037,16/04/26,11:48,Dineshkumar,,"{'neg': 0.0, 'neu': 0.0, 'pos': 0.0, 'compound...",0.000,0.0,0.0000,0.000,positive,2026-04-16 11:48:00,False,0
1038,16/04/26,11:48,Dineshkumar,Trois-1764,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.000,0.0,0.0000,1.000,positive,2026-04-16 11:48:00,False,0
1039,16/04/26,11:48,Dineshkumar,<Media omitted>,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.000,0.0,0.0000,1.000,positive,2026-04-16 11:48:00,False,3
1040,16/04/26,11:48,Dineshkumar,<Media omitted>,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.000,0.0,0.0000,1.000,positive,2026-04-16 11:48:00,False,3
1041,16/04/26,11:49,Jayabharathi,Okay,"{'neg': 0.0, 'neu': 0.0, 'pos': 1.0, 'compound...",1.000,0.0,0.2263,0.000,positive,2026-04-16 11:49:00,False,2

In [9]:
dataset['Topic'].value_counts()

Topic
0    343
3    256
2    157
4    153
1    133
Name: count, dtype: int64