In [4]:
import pandas as pd
dataset= pd.read_csv("whatsapp_output.csv", index_col=False)
dataset

,Date,Time,Name,Chat,scores,positive,negative,compound,neutral,com_score,datetime,is_flirt
0,29/04/25,11:15,Dineshkumar,What help do you need,"{'neg': 0.0, 'neu': 0.597, 'pos': 0.403, 'comp...",0.403,0.0,0.4019,0.597,positive,2025-04-29 11:15:00,False
1,29/04/25,12:14,Jayabharathi,One kiss,"{'neg': 0.0, 'neu': 0.263, 'pos': 0.737, 'comp...",0.737,0.0,0.4215,0.263,positive,2025-04-29 12:14:00,True
2,29/04/25,12:17,Jayabharathi,https://www.instagram.com/reel/Cb2VhXDPtaW/?i...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.000,0.0,0.0000,1.000,positive,2025-04-29 12:17:00,False
3,29/04/25,12:25,Jayabharathi,Like this,"{'neg': 0.0, 'neu': 0.286, 'pos': 0.714, 'comp...",0.714,0.0,0.3612,0.286,positive,2025-04-29 12:25:00,False
4,29/04/25,13:37,Dineshkumar,<Media omitted>,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.000,0.0,0.0000,1.000,positive,2025-04-29 13:37:00,False
...,...,...,...,...,...,...,...,...,...,...,...,...
1037,16/04/26,11:48,Dineshkumar,,"{'neg': 0.0, 'neu': 0.0, 'pos': 0.0, 'compound...",0.000,0.0,0.0000,0.000,positive,2026-04-16 11:48:00,False
1038,16/04/26,11:48,Dineshkumar,Trois-1764,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.000,0.0,0.0000,1.000,positive,2026-04-16 11:48:00,False
1039,16/04/26,11:48,Dineshkumar,<Media omitted>,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.000,0.0,0.0000,1.000,positive,2026-04-16 11:48:00,False
1040,16/04/26,11:48,Dineshkumar,<Media omitted>,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.000,0.0,0.0000,1.000,positive,2026-04-16 11:48:00,False
1041,16/04/26,11:49,Jayabharathi,Okay,"{'neg': 0.0, 'neu': 0.0, 'pos': 1.0, 'compound...",1.000,0.0,0.2263,0.000,positive,2026-04-16 11:49:00,False

In [5]:
# in topic modelling we do preprocessing technique
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(max_df=0.95, min_df=2, stop_words='english')
dtm=tfidf.fit_transform(dataset['Chat'])
dtm

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 2258 stored elements and shape (1042, 385)>

In [6]:
# create the model
from sklearn.decomposition import NMF
nmf=NMF(n_components=5, random_state=42)
nmf.fit(dtm)

NMF(n_components=5, random_state=42)

In [13]:
# show all topic in for loop
for index,topic in enumerate(nmf.components_):
    results=([tfidf.get_feature_names_out()[i] for i in topic.argsort()[-10:]])
    print(results)

['hy', 'sollu', 'onnu', 'love', 'yes', 'baby', 'deleted', 'message', 'media', 'omitted']
['just', 'month', 'sollala', 'vituren', 'da', 'di', 'va', 'ma', 'pa', 'ok']
['instagram', 'igsh', 'reel', 'www', 'youtu', 'youtube', 'shorts', 'si', 'com', 'https']
['dhan', 'ne', 'send', 'enaku', 'nu', 'la', 'okay', 'ah', 'na', 'enna']
['enakku', 'sollu', 'aachu', 'plan', 'panra', 'product', 'meesho', 'check', 'enna', 'hey']

In [16]:
topic_results=nmf.transform(dtm)
dataset["Topic"]=topic_results.argmax(axis=1)

In [17]:
dataset

,Date,Time,Name,Chat,scores,positive,negative,compound,neutral,com_score,datetime,is_flirt,Topic
0,29/04/25,11:15,Dineshkumar,What help do you need,"{'neg': 0.0, 'neu': 0.597, 'pos': 0.403, 'comp...",0.403,0.0,0.4019,0.597,positive,2025-04-29 11:15:00,False,3
1,29/04/25,12:14,Jayabharathi,One kiss,"{'neg': 0.0, 'neu': 0.263, 'pos': 0.737, 'comp...",0.737,0.0,0.4215,0.263,positive,2025-04-29 12:14:00,True,0
2,29/04/25,12:17,Jayabharathi,https://www.instagram.com/reel/Cb2VhXDPtaW/?i...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.000,0.0,0.0000,1.000,positive,2025-04-29 12:17:00,False,2
3,29/04/25,12:25,Jayabharathi,Like this,"{'neg': 0.0, 'neu': 0.286, 'pos': 0.714, 'comp...",0.714,0.0,0.3612,0.286,positive,2025-04-29 12:25:00,False,3
4,29/04/25,13:37,Dineshkumar,<Media omitted>,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.000,0.0,0.0000,1.000,positive,2025-04-29 13:37:00,False,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1037,16/04/26,11:48,Dineshkumar,,"{'neg': 0.0, 'neu': 0.0, 'pos': 0.0, 'compound...",0.000,0.0,0.0000,0.000,positive,2026-04-16 11:48:00,False,0
1038,16/04/26,11:48,Dineshkumar,Trois-1764,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.000,0.0,0.0000,1.000,positive,2026-04-16 11:48:00,False,0
1039,16/04/26,11:48,Dineshkumar,<Media omitted>,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.000,0.0,0.0000,1.000,positive,2026-04-16 11:48:00,False,0
1040,16/04/26,11:48,Dineshkumar,<Media omitted>,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.000,0.0,0.0000,1.000,positive,2026-04-16 11:48:00,False,0
1041,16/04/26,11:49,Jayabharathi,Okay,"{'neg': 0.0, 'neu': 0.0, 'pos': 1.0, 'compound...",1.000,0.0,0.2263,0.000,positive,2026-04-16 11:49:00,False,3

In [18]:
# check the repeated values
dataset['Topic'].value_counts()

Topic
3    468
0    416
2     59
4     50
1     49
Name: count, dtype: int64

In [19]:
!pip install wordCloud

Collecting wordCloud
  Downloading wordcloud-1.9.6-cp312-cp312-win_amd64.whl.metadata (3.5 kB)
Requirement already satisfied: numpy>=1.19.3 in C:\Anaconda\envs\aiml\Lib\site-packages (from wordCloud) (2.1.3)
Requirement already satisfied: pillow in C:\Anaconda\envs\aiml\Lib\site-packages (from wordCloud) (12.2.0)
Requirement already satisfied: matplotlib in C:\Anaconda\envs\aiml\Lib\site-packages (from wordCloud) (3.10.8)
Requirement already satisfied: contourpy>=1.0.1 in C:\Anaconda\envs\aiml\Lib\site-packages (from matplotlib->wordCloud) (1.3.3)
Requirement already satisfied: cycler>=0.10 in C:\Anaconda\envs\aiml\Lib\site-packages (from matplotlib->wordCloud) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in C:\Anaconda\envs\aiml\Lib\site-packages (from matplotlib->wordCloud) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Anaconda\envs\aiml\Lib\site-packages (from matplotlib->wordCloud) (1.5.0)
Requirement already satisfied: packaging>=20.0 in C:\Anaconda\envs\aiml\Lib\site-packages (from matplotlib->wordCloud) (26.0)
Requirement already satisfied: pyparsing>=3 in C:\Anaconda\envs\aiml\Lib\site-packages (from matplotlib->wordCloud) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in C:\Anaconda\envs\aiml\Lib\site-packages (from matplotlib->wordCloud) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in C:\Anaconda\envs\aiml\Lib\site-packages (from python-dateutil>=2.7->matplotlib->wordCloud) (1.17.0)
Downloading wordcloud-1.9.6-cp312-cp312-win_amd64.whl (307 kB)
Installing collected packages: wordCloud
Successfully installed wordCloud-1.9.6

In [21]:

from wordcloud import WordCloud
from nltk.corpus import stopwords
import nltk
import matplotlib.pyplot as plt
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\bavan\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [ ]:
comment_words = []
stoplist = stopwords.words('english')
stoplist.extend(['omitted', 'voice','missed','call','video','deleted','media','message'])
wordcloudss="This function saves image"
dataset.index=range(dataset.shape[0])
for i in range(1,len(dataset)): 
    comment_words.append(dataset['Chat'][i])
    vv=" ".join(comment_words)          
    wordcloud = WordCloud(width = 800, height = 800, 
                                background_color ='white', 
                                      stopwords = stoplist, 
                                      min_font_size = 10).generate(vv)         
plt.figure(figsize = (9, 7), facecolor = None)
plt.imshow(wordcloud)
plt.axis("off") 
plt.tight_layout(pad = 0) 
plt.savefig('wordcloud.PNG')
plt.show() 
print("Successfully created")
wordcloudss="This function saves image"