In [1]:
# upload the dataset, convert text file into table  format
import pandas as pd
dataset = pd.read_csv("chat.txt", header=None, on_bad_lines='skip', encoding='utf8')
dataset = dataset.drop(0)
dataset

             0                                                  1    2    3
1     29/04/25   11:15 - Disappearing messages were turned off...  NaN  NaN
2     29/04/25         11:15 - Dineshkumar: What help do you need  NaN  NaN
3     29/04/25                     12:14 - Jayabharathi: One kiss  NaN  NaN
4     29/04/25   12:17 - Jayabharathi: https://www.instagram.c...  NaN  NaN
5     29/04/25                    12:25 - Jayabharathi: Like this  NaN  NaN
...        ...                                                ...  ...  ...
1204  16/04/26                              11:48 - Dineshkumar:   NaN  NaN
1205  16/04/26                    11:48 - Dineshkumar: Trois-1764  NaN  NaN
1206  16/04/26               11:48 - Dineshkumar: <Media omitted>  NaN  NaN
1207  16/04/26               11:48 - Dineshkumar: <Media omitted>  NaN  NaN
1208  16/04/26                         11:49 - Jayabharathi: Okay  NaN  NaN

[1208 rows x 4 columns]

In [2]:
# check what data inside in 2 & 3 columns.
d=dataset[2].value_counts()
d

2
20                                                                                                                         2
 hotel and park                                                                                                            1
 thitturathu pesura vartha ellame ithu aprm enaku venam                                                                    1
 click this link:                                                                                                          1
 1 Small Container & 1 Spoon Ideal for Kids BPA Free 1120ml+70ml- Blue                                                     1
 payment of 904 has been successfully received against your order 2-004956509685.Ref Num# 10004738748182                   1
28 ok va                                                                                                                   1
 athai um epdi la ena pesunanga theriyuma                                                                                  1
000 credited                                                                                                               1
 energy-efficient                                                                                                          1
 tomato                                                                                                                    1
 avocado (optional)                                                                                                        1
 whole grains                                                                                                              1
 salmon) for omega-3s.                                                                                                     1
 download the OLX App: https://www.olx.in/openapp                                                                          1
  ₹ 20.0k/Month. Check out this beautiful property which I have found on Housing App https://dzfki.app.link/QbfSynVEP0b    1
78.11172                                                                                                                   1
 check out this product on Meesho!                                                                                         1
Name: count, dtype: int64

In [3]:
# concat two columns.
dataset[1] = dataset[1].fillna('')+ '' + dataset[2].fillna('')+ '' + dataset[3].fillna('')
dataset[1]

1        11:15 - Disappearing messages were turned off...
2              11:15 - Dineshkumar: What help do you need
3                          12:14 - Jayabharathi: One kiss
4        12:17 - Jayabharathi: https://www.instagram.c...
5                         12:25 - Jayabharathi: Like this
                              ...
1204                                11:48 - Dineshkumar:
1205                      11:48 - Dineshkumar: Trois-1764
1206                 11:48 - Dineshkumar: <Media omitted>
1207                 11:48 - Dineshkumar: <Media omitted>
1208                           11:49 - Jayabharathi: Okay
Name: 1, Length: 1208, dtype: object

In [4]:
dataset = dataset[[0, 1]]
dataset

             0                                                  1
1     29/04/25   11:15 - Disappearing messages were turned off...
2     29/04/25         11:15 - Dineshkumar: What help do you need
3     29/04/25                     12:14 - Jayabharathi: One kiss
4     29/04/25   12:17 - Jayabharathi: https://www.instagram.c...
5     29/04/25                    12:25 - Jayabharathi: Like this
...        ...                                                ...
1204  16/04/26                              11:48 - Dineshkumar:
1205  16/04/26                    11:48 - Dineshkumar: Trois-1764
1206  16/04/26               11:48 - Dineshkumar: <Media omitted>
1207  16/04/26               11:48 - Dineshkumar: <Media omitted>
1208  16/04/26                         11:49 - Jayabharathi: Okay

[1208 rows x 2 columns]

In [5]:
# drop unnesscary rows/records. and name the columns.
dataset = dataset.drop(1)
dataset.columns= ['Date', 'Chat']
dataset

          Date                                               Chat
2     29/04/25         11:15 - Dineshkumar: What help do you need
3     29/04/25                     12:14 - Jayabharathi: One kiss
4     29/04/25   12:17 - Jayabharathi: https://www.instagram.c...
5     29/04/25                    12:25 - Jayabharathi: Like this
6     29/04/25               13:37 - Dineshkumar: <Media omitted>
...        ...                                                ...
1204  16/04/26                              11:48 - Dineshkumar:
1205  16/04/26                    11:48 - Dineshkumar: Trois-1764
1206  16/04/26               11:48 - Dineshkumar: <Media omitted>
1207  16/04/26               11:48 - Dineshkumar: <Media omitted>
1208  16/04/26                         11:49 - Jayabharathi: Okay

[1207 rows x 2 columns]

In [6]:
# from the chat, split time and chat and also add the column in the dataset.
df1=dataset['Chat'].str.split('-', n=1, expand=True)
dataset['Time'] = df1[0]

In [7]:
df1

            0                                                  1
2      11:15                  Dineshkumar: What help do you need
3      12:14                              Jayabharathi: One kiss
4      12:17    Jayabharathi: https://www.instagram.com/reel/...
5      12:25                             Jayabharathi: Like this
6      13:37                        Dineshkumar: <Media omitted>
...       ...                                                ...
1204   11:48                                       Dineshkumar:
1205   11:48                             Dineshkumar: Trois-1764
1206   11:48                        Dineshkumar: <Media omitted>
1207   11:48                        Dineshkumar: <Media omitted>
1208   11:49                                  Jayabharathi: Okay

[1207 rows x 2 columns]

In [8]:
# split 1 column, as name and message. and add new column in the dataset.
df2= df1[1].str.split(':', n=1, expand=True)
dataset['Name']= df2[0]
dataset['Chat']= df2[1]

In [9]:
dataset

,Date,Chat,Time,Name
2,29/04/25,What help do you need,11:15,Dineshkumar
3,29/04/25,One kiss,12:14,Jayabharathi
4,29/04/25,https://www.instagram.com/reel/Cb2VhXDPtaW/?i...,12:17,Jayabharathi
5,29/04/25,Like this,12:25,Jayabharathi
6,29/04/25,<Media omitted>,13:37,Dineshkumar
...,...,...,...,...
1204,16/04/26,,11:48,Dineshkumar
1205,16/04/26,Trois-1764,11:48,Dineshkumar
1206,16/04/26,<Media omitted>,11:48,Dineshkumar
1207,16/04/26,<Media omitted>,11:48,Dineshkumar
1208,16/04/26,Okay,11:49,Jayabharathi

In [11]:
# rearrange the column.
dataset=dataset[['Date','Time', 'Name', 'Chat']]
dataset

,Date,Time,Name,Chat
2,29/04/25,11:15,Dineshkumar,What help do you need
3,29/04/25,12:14,Jayabharathi,One kiss
4,29/04/25,12:17,Jayabharathi,https://www.instagram.com/reel/Cb2VhXDPtaW/?i...
5,29/04/25,12:25,Jayabharathi,Like this
6,29/04/25,13:37,Dineshkumar,<Media omitted>
...,...,...,...,...
1204,16/04/26,11:48,Dineshkumar,
1205,16/04/26,11:48,Dineshkumar,Trois-1764
1206,16/04/26,11:48,Dineshkumar,<Media omitted>
1207,16/04/26,11:48,Dineshkumar,<Media omitted>
1208,16/04/26,11:49,Jayabharathi,Okay

In [12]:
dataset = dataset[
    dataset['Name'] != "have-rental-homes-2bhk-home-3bhk-iid-1832564386 For the best experience download the OLX App"
]

In [13]:
dataset

,Date,Time,Name,Chat
2,29/04/25,11:15,Dineshkumar,What help do you need
3,29/04/25,12:14,Jayabharathi,One kiss
4,29/04/25,12:17,Jayabharathi,https://www.instagram.com/reel/Cb2VhXDPtaW/?i...
5,29/04/25,12:25,Jayabharathi,Like this
6,29/04/25,13:37,Dineshkumar,<Media omitted>
...,...,...,...,...
1204,16/04/26,11:48,Dineshkumar,
1205,16/04/26,11:48,Dineshkumar,Trois-1764
1206,16/04/26,11:48,Dineshkumar,<Media omitted>
1207,16/04/26,11:48,Dineshkumar,<Media omitted>
1208,16/04/26,11:49,Jayabharathi,Okay

In [14]:
# check the information.
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1206 entries, 2 to 1208
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    1206 non-null   object
 1   Time    1206 non-null   object
 2   Name    1043 non-null   object
 3   Chat    1042 non-null   object
dtypes: object(4)
memory usage: 47.1+ KB

In [16]:
import nltk
nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\bavan\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

True

In [17]:
!pip install nltk

Requirement already satisfied: nltk in C:\Anaconda\envs\aiml\Lib\site-packages (3.9.4)
Requirement already satisfied: click in C:\Anaconda\envs\aiml\Lib\site-packages (from nltk) (8.3.2)
Requirement already satisfied: joblib in C:\Anaconda\envs\aiml\Lib\site-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in C:\Anaconda\envs\aiml\Lib\site-packages (from nltk) (2026.4.4)
Requirement already satisfied: tqdm in C:\Anaconda\envs\aiml\Lib\site-packages (from nltk) (4.67.3)
Requirement already satisfied: colorama in C:\Anaconda\envs\aiml\Lib\site-packages (from click->nltk) (0.4.6)

In [15]:
dataset.dropna(inplace=True)

C:\Users\bavan\AppData\Local\Temp\ipykernel_8952\2639109627.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset.dropna(inplace=True)

In [18]:
# create a model. and get analyze the single value.
from nltk.sentiment.vader import SentimentIntensityAnalyzer
sid = SentimentIntensityAnalyzer()
senti = sid.polarity_scores(dataset['Chat'][5])
senti

{'neg': 0.0, 'neu': 0.286, 'pos': 0.714, 'compound': 0.3612}

In [19]:
# add all the value in the dataset table.
dataset['scores'] = dataset['Chat'].apply(lambda commontext:sid.polarity_scores(commontext))
dataset['positive'] = dataset['scores'].apply(lambda score_dict: score_dict['pos'])
dataset['negative'] = dataset['scores'].apply(lambda score_dict: score_dict['neg'])
dataset['compound'] = dataset['scores'].apply(lambda score_dict: score_dict['compound'])
dataset['neutral'] = dataset['scores'].apply(lambda score_dict: score_dict['neu'])

C:\Users\bavan\AppData\Local\Temp\ipykernel_8952\1290800242.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset['scores'] = dataset['Chat'].apply(lambda commontext:sid.polarity_scores(commontext))
C:\Users\bavan\AppData\Local\Temp\ipykernel_8952\1290800242.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset['positive'] = dataset['scores'].apply(lambda score_dict: score_dict['pos'])
C:\Users\bavan\AppData\Local\Temp\ipykernel_8952\1290800242.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset['negative'] = dataset['scores'].apply(lambda score_dict: score_dict['neg'])
C:\Users\bavan\AppData\Local\Temp\ipykernel_8952\1290800242.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset['compound'] = dataset['scores'].apply(lambda score_dict: score_dict['compound'])
C:\Users\bavan\AppData\Local\Temp\ipykernel_8952\1290800242.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset['neutral'] = dataset['scores'].apply(lambda score_dict: score_dict['neu'])

In [20]:
# check which chat is positive or negative
dataset['com_score'] = dataset['compound'].apply(lambda c: 'positive' if c >=0 else 'negative')
# create a table for this,
posneg = pd.DataFrame(dataset['com_score'].value_counts())
posneg

C:\Users\bavan\AppData\Local\Temp\ipykernel_8952\2461251916.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset['com_score'] = dataset['compound'].apply(lambda c: 'positive' if c >=0 else 'negative')

           count
com_score
positive     986
negative      56

### who is talkative?

In [21]:
msg_count = dataset['Name'].value_counts()
print(msg_count)

Name
Jayabharathi    567
Dineshkumar     475
Name: count, dtype: int64

In [22]:
dataset

,Date,Time,Name,Chat,scores,positive,negative,compound,neutral,com_score
2,29/04/25,11:15,Dineshkumar,What help do you need,"{'neg': 0.0, 'neu': 0.597, 'pos': 0.403, 'comp...",0.403,0.0,0.4019,0.597,positive
3,29/04/25,12:14,Jayabharathi,One kiss,"{'neg': 0.0, 'neu': 0.263, 'pos': 0.737, 'comp...",0.737,0.0,0.4215,0.263,positive
4,29/04/25,12:17,Jayabharathi,https://www.instagram.com/reel/Cb2VhXDPtaW/?i...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.000,0.0,0.0000,1.000,positive
5,29/04/25,12:25,Jayabharathi,Like this,"{'neg': 0.0, 'neu': 0.286, 'pos': 0.714, 'comp...",0.714,0.0,0.3612,0.286,positive
6,29/04/25,13:37,Dineshkumar,<Media omitted>,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.000,0.0,0.0000,1.000,positive
...,...,...,...,...,...,...,...,...,...,...
1204,16/04/26,11:48,Dineshkumar,,"{'neg': 0.0, 'neu': 0.0, 'pos': 0.0, 'compound...",0.000,0.0,0.0000,0.000,positive
1205,16/04/26,11:48,Dineshkumar,Trois-1764,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.000,0.0,0.0000,1.000,positive
1206,16/04/26,11:48,Dineshkumar,<Media omitted>,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.000,0.0,0.0000,1.000,positive
1207,16/04/26,11:48,Dineshkumar,<Media omitted>,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.000,0.0,0.0000,1.000,positive
1208,16/04/26,11:49,Jayabharathi,Okay,"{'neg': 0.0, 'neu': 0.0, 'pos': 1.0, 'compound...",1.000,0.0,0.2263,0.000,positive

In [23]:
# who is talkative view name? used by talkative.
talkative = msg_count.idxmax()
print("Talkative:", talkative)

Talkative:  Jayabharathi

### who is less talkative?

In [24]:
less_talkative = msg_count.idxmin()
print("Less talkative:", less_talkative)

Less talkative:  Dineshkumar

### most active date

In [25]:
dataset['datetime'] = pd.to_datetime(dataset['Date']+ ' ' +dataset['Time'])

C:\Users\bavan\AppData\Local\Temp\ipykernel_8952\3844591403.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dataset['datetime'] = pd.to_datetime(dataset['Date']+ ' ' +dataset['Time'])
C:\Users\bavan\AppData\Local\Temp\ipykernel_8952\3844591403.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset['datetime'] = pd.to_datetime(dataset['Date']+ ' ' +dataset['Time'])

In [29]:
active = dataset['Date'].value_counts()
active = active.idxmax()
print("Most active date:", active)

Most active date: 07/09/25

### most active day

In [33]:
day =  dataset['datetime'].dt.day_name().value_counts()
day= day.idxmax()
print("Most Active day:", day)

Most Active day: Wednesday

### most active hours

In [37]:
hours = dataset['datetime'].dt.hour.value_counts().idxmax()
print("Most active hours:", hours)

Most active hours: 13

### average number of message per day

In [38]:
avg = dataset['datetime'].dt.date.value_counts().mean()
avg

np.float64(6.023121387283237)

### media sharing count

In [43]:
media_count = sum(dataset['Chat'].str.contains("<Media omitted>", na=False))
print('Media_count:',media_count)

Media_count: 194

### deleted message count

In [48]:
Deleted= sum(dataset['Chat'].str.contains("deleted", case=False, na=False))
print("deleted_message:", Deleted)

deleted_message: 13

### missed voice call

In [49]:
missed_voice = sum(dataset['Chat'].str.contains('Missed voice call', case=False, na=False))
print("Missed Voice Call Count:", missed_voice)

Missed Voice Call Count: 0

### missed video call

In [50]:
missed_voice = sum(dataset['Chat'].str.contains('Missed video call', case=False, na=False))
print("Missed Voice Call Count:", missed_voice)

Missed Voice Call Count: 0

In [52]:
flirt_data= pd.read_csv("flirt.txt",  header=None, on_bad_lines='skip', encoding='utf8')
flirt_data

                     0
0                 love
1                  luv
2                 dear
3              darling
4                 baby
5                 babe
6           sweetheart
7              sweetie
8                cutie
9             handsome
10           beautiful
11              pretty
12            gorgeous
13                 hot
14                sexy
15                kiss
16              kisses
17                 hug
18                hugs
19            miss you
20              miss u
21     thinking of you
22  thinking about you
23          i like you
24          i love you
25               luv u
26               heart
27                  ❤️
28                   😍
29                   😘
30                   😜
31                   😉
32                   💋
33                   💕
34                   💖
35            romantic
36                date
37               crush
38             my love
39             my dear
40             my baby
41       my sweetheart

### flirt percentage by Dineshkumar

In [53]:
flirt_words = flirt_data[0].str.lower().tolist()
flirt_words

['love',
 'luv',
 'dear',
 'darling',
 'baby',
 'babe',
 'sweetheart',
 'sweetie',
 'cutie',
 'handsome',
 'beautiful',
 'pretty',
 'gorgeous',
 'hot',
 'sexy',
 'kiss',
 'kisses',
 'hug',
 'hugs',
 'miss you',
 'miss u',
 'thinking of you',
 'thinking about you',
 'i like you',
 'i love you',
 'luv u',
 'heart',
 '❤️',
 '😍',
 '😘',
 '😜',
 '😉',
 '💋',
 '💕',
 '💖',
 'romantic',
 'date',
 'crush',
 'my love',
 'my dear',
 'my baby',
 'my sweetheart']

In [56]:
dataset['is_flirt']=dataset['Chat'].str.lower().apply(lambda msg : any(words in msg for words in flirt_words))

C:\Users\bavan\AppData\Local\Temp\ipykernel_8952\348079560.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset['is_flirt']=dataset['Chat'].str.lower().apply(lambda msg : any(words in msg for words in flirt_words))

In [57]:
dataset

,Date,Time,Name,Chat,scores,positive,negative,compound,neutral,com_score,datetime,is_flirt
2,29/04/25,11:15,Dineshkumar,What help do you need,"{'neg': 0.0, 'neu': 0.597, 'pos': 0.403, 'comp...",0.403,0.0,0.4019,0.597,positive,2025-04-29 11:15:00,False
3,29/04/25,12:14,Jayabharathi,One kiss,"{'neg': 0.0, 'neu': 0.263, 'pos': 0.737, 'comp...",0.737,0.0,0.4215,0.263,positive,2025-04-29 12:14:00,True
4,29/04/25,12:17,Jayabharathi,https://www.instagram.com/reel/Cb2VhXDPtaW/?i...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.000,0.0,0.0000,1.000,positive,2025-04-29 12:17:00,False
5,29/04/25,12:25,Jayabharathi,Like this,"{'neg': 0.0, 'neu': 0.286, 'pos': 0.714, 'comp...",0.714,0.0,0.3612,0.286,positive,2025-04-29 12:25:00,False
6,29/04/25,13:37,Dineshkumar,<Media omitted>,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.000,0.0,0.0000,1.000,positive,2025-04-29 13:37:00,False
...,...,...,...,...,...,...,...,...,...,...,...,...
1204,16/04/26,11:48,Dineshkumar,,"{'neg': 0.0, 'neu': 0.0, 'pos': 0.0, 'compound...",0.000,0.0,0.0000,0.000,positive,2026-04-16 11:48:00,False
1205,16/04/26,11:48,Dineshkumar,Trois-1764,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.000,0.0,0.0000,1.000,positive,2026-04-16 11:48:00,False
1206,16/04/26,11:48,Dineshkumar,<Media omitted>,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.000,0.0,0.0000,1.000,positive,2026-04-16 11:48:00,False
1207,16/04/26,11:48,Dineshkumar,<Media omitted>,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.000,0.0,0.0000,1.000,positive,2026-04-16 11:48:00,False
1208,16/04/26,11:49,Jayabharathi,Okay,"{'neg': 0.0, 'neu': 0.0, 'pos': 1.0, 'compound...",1.000,0.0,0.2263,0.000,positive,2026-04-16 11:49:00,False

In [77]:
dataset.to_csv("whatsapp_output.csv", index=False)

In [76]:
flirt_percentage =dataset.groupby('Name') ['is_flirt'].mean() * 100
flirt_percentage = flirt_percentage.to_frame(name='Flirt %')
flirt_percentage

               Flirt %
Name
Dineshkumar   5.684211
Jayabharathi  3.350970

In [65]:
name = flirt_percentage.idxmax()
print("who get high flirt_percentage:", name)

who get high flirt_percentage:  Dineshkumar